CREATE TABLE Usuario (
    id BIGINT IDENTITY(1,1) NOT NULL,
    nome VARCHAR(255) NOT NULL,
    CONSTRAINT PK_Usuario PRIMARY KEY (id)
);
CREATE TABLE LIVRO (
    id BIGINT IDENTITY(1,1) NOT NULL,
    nome VARCHAR(255) NOT NULL,
    usuario_id BIGINT NOT NULL,
    CONSTRAINT PK_Livro PRIMARY KEY (id),
    CONSTRAINT FK_Usuario_Livro FOREIGN KEY (usuario_id)
    REFERENCES Usuario(id) ON DELETE CASCADE
);